// Generated by CoffeeScript 1.10.0
(function() {
  var Trello, client, key, token;

  key = process.env.TRELLO_KEY;

  token = process.env.TRELLO_TOKEN;

  Trello = require('../lib');

  client = Trello(key, token);

  client.createBoard({
    name: 'test board'
  }).then(function(result) {
    console.log('done');
    return console.dir(result);
  })["catch"](function(err) {
    console.log('error');
    return console.dir(err);
  });

}).call(this);
