// Generated by CoffeeScript 1.12.3
(function() {
  var api, exec, transform;

  transform = require('lodash.transform');

  api = require('../api.json');

  exec = require('./_exec');

  module.exports = transform(api, function(memo, apiDesc, apiId) {
    return memo[apiDesc.name] = function(params) {
      return exec(apiId, params);
    };
  });

}).call(this);
