// Generated by CoffeeScript 1.10.0
(function() {
  var api, exclude, path, renamer, requireDirectory;

  path = require('path');

  requireDirectory = require('require-directory');

  api = require('../api.json');

  exclude = function(filepath) {
    var filename;
    filename = path.basename(filepath);
    return /^index\./.test(filename) || /^_/.test(filename) || /\.json$/.test(filename);
  };

  renamer = function(name) {
    return api[name].name;
  };

  module.exports = requireDirectory(module, {
    exclude: exclude,
    rename: renamer
  });

}).call(this);
