// Generated by CoffeeScript 1.12.3
(function() {
  var Promise, api, req, request, validate, varString;

  request = require('request-promise');

  Promise = require('bluebird');

  validate = require('./_validate');

  varString = require('./_varString');

  api = require('../api.json');

  req = request.defaults({
    baseUrl: 'https://api.trello.com/1/',
    json: true,
    headers: {
      Accept: 'application/json'
    }
  });

  module.exports = function(ns, values) {
    var err, key, options, token;
    err = validate(ns, values);
    if (err) {
      return Promise.reject(err);
    }
    key = values.key;
    token = values.token;
    options = {
      method: api[ns].method,
      uri: varString.replace(api[ns].url, values),
      body: values
    };
    console.log(options);
    varString.getVars(api[ns].url).forEach(function(varName) {
      return delete options.body[varName];
    });
    console.log(options);
    if (api[ns].method === 'GET') {
      if (options.uri.indexOf('?') > -1) {
        options.uri += "&";
      } else {
        options.uri += "?";
      }
      options.uri += "key=" + key + "&token=" + token;
    }
    return req(options);
  };

}).call(this);
