// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, api, req, request, validate, varString;

  request = require('request-promise');

  Promise = require('bluebird');

  validate = require('./_validate');

  varString = require('./_varString');

  api = require('../api.json');

  req = request.defaults({
    baseUrl: 'https://api.trello.com/1/',
    json: true,
    headers: {
      Accept: 'application/json'
    }
  });

  module.exports = function(ns, values) {
    var err, options;
    err = validate(ns, values);
    if (err) {
      return Promise.reject(err);
    }
    options = {
      method: api[ns].method,
      uri: varString.replace(api[ns].url, values),
      body: values
    };
    varString.getVars(api[ns].url).forEach(function(varName) {
      return delete options.body[varName];
    });
    return req(options);
  };

}).call(this);
