// Generated by CoffeeScript 1.12.3
(function() {
  var api;

  api = require('../api.json');

  module.exports = function(method, params) {
    var bullets, err, missing, msg, required;
    required = api[method].params.filter(function(p) {
      return p.required === 'Required';
    });
    missing = required.filter(function(p) {
      return typeof params[p.name] === 'undefined';
    });
    err = false;
    if (missing.length) {
      bullets = missing.map(function(param) {
        return "- " + param.name + " ... " + param.description;
      });
      msg = method + " missing params:\n" + (bullets.join('\n'));
      err = new Error(msg);
    }
    return err;
  };

}).call(this);
